### ISSUE TITLE
open PRs that should be merged

### ISSUE THREAD

**Issue by pmario** [Jermolene/TiddlyWiki5#2642]
As discussed in hangout 101

- [x] #2631 german lang update
- [x] #2641 second try / fix for 2634 week calculation .. as requested
- [x] #2623 update chinese translation

documentation only.

- [x] #2201 updates to overall operators docs 

edit-mode: set tag with enter key.

- [x] #2593 allows to define the tag for keyboard widget ... depend on 
- [x] #2592 allows to add a new tagname hitting enter

"needs-work" label was set because documentation was missing. docs is done now. 

- [x] #1954 harmonization of switcher styles and usage (also see #1099 style for palettechoser)
- [x] #2031 allows to retain tab contents 
- [x] #2066 has:field — tested & documented
- [x] #2182 sets checked class for radio widget wrapper / label 
- [x] #2104 allow radio widget to set an index in a data tiddler 
- [x] #2103 allows checkbox widget to set an index in a data tiddler 
- [x] #2072 provides a "close plugin library" button

**Comment by BramChen** [comment]
languages updates: 
- [ ] #2621 fixes #2620 - Correct DateFormat in Portuguese
- [ ] #2622 signed the Contributor License Agreement (@nmota)

**Comment by gernert** [comment]
- [ ] Danish translation for 5.1.14 http://tw5danish.tiddlyspot.com/
- [ ] Dutch translation for 5.1.14 http://tw5dutch.tiddlyspot.com/

**Comment by Evolena** [comment]
#1954 can be checked.

**Comment by pmario** [comment]
:)
