### ISSUE TITLE
Plans for v5.1.19

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#3642]
I propose to release v5.1.19 over the next couple of days as a bug fix release that addresses the following issues:

* [x] #3630 - incompatible change to the way that the download filename is constructed
* [x] #3641 - regression with search logic
* [x] #3625 - empty.html accidentally includes a splash screen
* [x] #3640 - fix KaTeX fonts
* [x] #3633 and any other outstanding documentation changes
* [x] #3647 - WebServer: Forced basic authentication broken
* [x] #3650 - button widget not refreshing when popupTitle changes

Work on #3623 will be deferred until v5.1.20.

**Comment by Jermolene** [comment]
Hi @AnthonyMuscio v5.1.19 is a bug fix release that won't have any new features beyond the changes discussed above.

**Comment by Jermolene** [comment]
Update: added another v5.1.18 bug: #3647

**Comment by diego898** [comment]
Hey @Jermolene, can we make one of these for 5.1.20? I like these overviews - we can even use githubs built in "milestones" to accomplish this as well.

**Comment by Jermolene** [comment]
Hi @diego898 I usually create issues like this when we're doing the final countdown to a release. Earlier on, I think we're better off using milestones as you suggest (I've been using labels for "v5.1.20" etc. because I'd forgotten milestones existed 🤷‍♂️).
