### ISSUE TITLE
Planning bug fix release v5.3.1

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyWiki5#7620]
I am planning to release TiddlyWiki v5.3.1 in order to get the following changes out:

* [x] Fixing #7592  by merging #7647
* [x] Update #4624 not to raise an error when a global assignment is detected and instead just to print a warning by merging #7648
* [x] Subject to further review, potentially revert #7468 to resolve performance regression on removing widgets from the widget tree
* [x] Fixing #7625 by reverting #7219
* [x] Merging #7622

Planned schedule:

* [x] ~~24th~~31st July prerelease frozen to further changes, and an announcement posted to the forum
* [x] ~~7th~~ 18th-21st August release of v5.3.1

**Comment by pmario** [comment]
@Jermolene .. Please also let us also fix this one:  **[BUG] Drag and drop from Google Chrome to Firefox fails #7440**

**Comment by CrossEye** [comment]
A minor question: Is the above list everything that would go into the release, or just the important things you're focusing on?  Do you cherry pick the commits for this or publish the trunk?

I only ask because I want to know if [the following](https://github.com/Jermolene/TiddlyWiki5/pull/7594/files#diff-a41e49f531d6bfd5c900e16e166b9623202706e7fe83fcbe12b339b11ce42b20L44)

```diff
  |size |The number of rows to display in multiple selection mode |
  |actions |A string containing ActionWidgets to be triggered when the key combination is detected |
  |focus |<<.from-version "5.2.4">> Optional. Set to "yes" to automatically focus the HTML select element after creation |
+ |tabindex |<<.from-version "5.3.1">> Optional. Sets the `tabindex` attribute of the HTML select element to the given value |
  ! Examples
```

was presumptuous, and whether we will need to go back and change #7594 to update the release version when it actually is deployed.

**Comment by pmario** [comment]
Usually it's the state of the https://tiddlywiki.com/prerelease/ that will go into a new version. So if something is merged already now, it should be part of the new release. 

Except if it interferes with the issues listed in the OP. Code related to the issues may be changed for the new release.

**Comment by Jermolene** [comment]
Hi @CrossEye thanks @pmario 

> A minor question: Is the above list everything that would go into the release, or just the important things you're focusing on? Do you cherry pick the commits for this or publish the trunk?

Everything on master will be included in v5.3.1, unless any problems turn up during testing.

**Comment by saqimtiaz** [comment]
Recommend that we include #7624 which is a bug fix for the missing indentation support for the pragmas introduced in v5.3.0

**Comment by Jermolene** [comment]
> Recommend that we include #7624 which is a bug fix for the missing indentation support for the pragmas introduced in v5.3.0

Thanks @saqimtiaz I've merged that.

**Comment by saqimtiaz** [comment]
Suggest we revert #7468 due to [potential performance considerations](https://github.com/Jermolene/TiddlyWiki5/pull/7468#issuecomment-1645753857).

**Comment by flibbles** [comment]
I have several plugins that are having trouble with v5.3.0 because they work with the parse tree.

1. They look for macrocalls in the parseTreeNode and can no longer find them (They're transcludes now)
2. They look for transcludes in the parseTreeNode and can no longer parse them (because their "tiddler" attribute has changed to "$tiddler")

I can easily migrate my plugins, but these are backward breaking changes. I don't care if they're rolled back or not, but I would like to know, because it'll change how I migrate my plugins.

**Comment by Jermolene** [comment]
> I can easily migrate my plugins, but these are backward breaking changes. I don't care if they're rolled back or not, but I would like to know, because it'll change how I migrate my plugins.

Hi @flibbles as we've discussed elsewhere, it is very unfortunate that we didn't identify these problems before the release of v5.3.0. I am not planning to revert these changes. I'd prefer to work on better integration between the core and relink, so that things are not so brittle in the future.

**Comment by Jermolene** [comment]
I've missed a few days with COVID (again!), but recovering well and now getting back up to speed. I've updated the schedule in the OP.

**Comment by Jermolene** [comment]
We are now entering the prerelease freeze for v5.3.1, where no further PRs will be merged until after the release on August 7th (apart from documentation).

**Comment by rmunn** [comment]
I just noticed that https://github.com/Jermolene/TiddlyWiki5/pull/7448 has a comment on it about a bug I introduced, which I have pulled out into a GitHub issue at https://github.com/Jermolene/TiddlyWiki5/issues/7678. I have a bugfix PR ready at https://github.com/Jermolene/TiddlyWiki5/pull/7679. I know it's late in the prerelease freeze, but it's a very short bugfix (two lines of code, plus one line fixing a code-style issue in the same file) and should be very easy to test. @Jermolene, would it be possible to get this bugfix reviewed in time to go into 7.3.1?

**Comment by pmario** [comment]
@Jermolene ... You may check the last 2 elements and then close this one. Well done! :)

**Comment by flibbles** [comment]
This release doesn't seem to break anything of mine. Thanks!

**Comment by Jermolene** [comment]
Thank you @pmario
